### ISSUE TITLE
Crash for reasons unknown

### ISSUE THREAD

**Issue by SirHaesslich** [gygrazok/witchmod#11]
Game crashed when entering the first fight of the run aka first room after Neow.

Exception in thread "LWJGL Application" com.badlogic.gdx.utils.GdxRuntimeException: java.lang.NoSuchMethodError: com.megacrit.cardcrawl.actions.common.MakeTempCardInDrawPileAction.<init>(Lcom/megacrit/cardcrawl/core/AbstractCreature;Lcom/megacrit/cardcrawl/core/AbstractCreature;Lcom/megacrit/cardcrawl/cards/AbstractCard;IZZ)V
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:133)
Caused by: java.lang.NoSuchMethodError: com.megacrit.cardcrawl.actions.common.MakeTempCardInDrawPileAction.<init>(Lcom/megacrit/cardcrawl/core/AbstractCreature;Lcom/megacrit/cardcrawl/core/AbstractCreature;Lcom/megacrit/cardcrawl/cards/AbstractCard;IZZ)V
	at witchmod.relics.BlackCat.atBattleStartPreDraw(BlackCat.java:36)
	at com.megacrit.cardcrawl.characters.AbstractPlayer.applyStartOfCombatPreDrawLogic(AbstractPlayer.java:2166)
	at com.megacrit.cardcrawl.rooms.AbstractRoom.update(AbstractRoom.java:237)
	at com.megacrit.cardcrawl.dungeons.AbstractDungeon.update(AbstractDungeon.java:2615)
	at com.megacrit.cardcrawl.core.CardCrawlGame.update(CardCrawlGame.java:825)
	at com.megacrit.cardcrawl.core.CardCrawlGame.render(CardCrawlGame.java:376)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:225)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126)

**Comment by KongMD-Steam** [comment]
I'm getting the same crash with the same exception message.

**Comment by gygrazok** [comment]
Probably a compatibility issue with the latest patch. I will look into it, thanks

**Comment by KongMD-Steam** [comment]
The devs changed the arguments for the MakeTempCardInDrawPileAction function. Here's the fix: https://github.com/gskleres/FruityMod-StS/commit/68d95fbb5ebdfebd295b7fda221470af54027dd7

**Comment by gygrazok** [comment]
Fixed. Thanks
