### ISSUE TITLE
StackOverFlowError when Act 3 elite puts burns in deck. Related to Mystic Unburial

### ISSUE THREAD

**Issue by SilentJ28** [gygrazok/witchmod#12]
Fighting pair of elites that put burns in deck in Act 3. Deck has an unupgraded mystic burial and discard has an upgraded mystic burial.

3/3 repro
turn 1: Malady right, defend, soul barrier+, mystic unburial twice (defend), pain bolt right
turn 2: Mortuus claw+ left, Runic Fang+ left, Defend
Remaining enemy then uses put burns in deck attack and exception is hit

[WITCH.autosave.zip](https://github.com/gygrazok/witchmod/files/2144036/WITCH.autosave.zip)

Enabled Mods: Base Mod, Always Neow, Witch

Exception in thread "LWJGL Application" com.badlogic.gdx.utils.GdxRuntimeException: java.lang.StackOverflowError
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:133)
Caused by: java.lang.StackOverflowError
	at witchmod.cards.MysticUnburial.canUse(MysticUnburial.java:36)
	at witchmod.cards.MysticUnburial.canUse(MysticUnburial.java:38)
	at witchmod.cards.MysticUnburial.canUse(MysticUnburial.java:38)
	at witchmod.cards.MysticUnburial.canUse(MysticUnburial.java:38)

**Comment by SilentJ28** [comment]
When I didn't play either Mystic Unburial I can finish the fight without issue

**Comment by gygrazok** [comment]
Fixed due to Mystic Unburial rework
