### ISSUE TITLE
Fatal Ray crash

### ISSUE THREAD

**Issue by SilentJ28** [gygrazok/witchmod#26]
Start of fight vs Nemesis. Cast owl to draw 2 cards and then tried to cast fatal ray. Game then froze.

Exception in thread "LWJGL Application" com.badlogic.gdx.utils.GdxRuntimeException: java.lang.NoSuchMethodError: com.megacrit.cardcrawl.vfx.combat.MindblastEffect.<init>(FF)V
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:133)
Caused by: java.lang.NoSuchMethodError: com.megacrit.cardcrawl.vfx.combat.MindblastEffect.<init>(FF)V
	at witchmod.cards.FatalRay.use(FatalRay.java:38)
	at com.megacrit.cardcrawl.characters.AbstractPlayer.useCard(AbstractPlayer.java:1476)
	at com.megacrit.cardcrawl.actions.GameActionManager.getNextAction(GameActionManager.java:294)
	at com.megacrit.cardcrawl.actions.GameActionManager.update(GameActionManager.java:148)
	at com.megacrit.cardcrawl.rooms.AbstractRoom.update(AbstractRoom.java:258)
	at com.megacrit.cardcrawl.dungeons.AbstractDungeon.update(AbstractDungeon.java:2674)
	at com.megacrit.cardcrawl.core.CardCrawlGame.update(CardCrawlGame.java:893)
	at com.megacrit.cardcrawl.core.CardCrawlGame.render(CardCrawlGame.java:466)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:225)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126)

**Comment by SilentJ28** [comment]
Had the relic that gives a random familiar at the start of each turn so starting 5 + owl meant I had 7 cards after drawing 2 and drawing the fatal ray

Reloaded game and did the same actions and it crashed again

**Comment by gygrazok** [comment]
Fixed in the new release, thanks for the report.

**Comment by SilentJ28** [comment]
@gygrazok What was the bug here? I am seeing the same bug with VoidRay on the Seeker mod.

**Comment by SilentJ28** [comment]
Ah I looked at the commit and see the fix. Will let the Seeker dev know too.
